### ISSUE TITLE
[BUG/ISSUE] Flashing/lag effect due to running 2 instances at once

### ISSUE THREAD

**Issue by DandelionSprout** [marticliment/ElevenClock#1098]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock** (3.9.6; Microsoft Store version)
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again** (I uninstalled the official site download version at least once and replaced it with the Microsoft Store version.)
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug

For reasons I've struggled surprisingly much to figure out for some weeks, ElevenClock opens up a 2nd instance approx. once a day (Most likely after update checks), causing a flashing/lag effect on the clock, as can be seen in the animated screenshot below.

## To Reproduce
Steps to reproduce the behaviour:

1) Install ElevenClock.
2) Set ElevenClock to start up on system boot.
3) Ensure that "Look for updates automatically" is turned on.
4) Ensure that the seconds counter is turned on.
5) Ensure that the ElevenClock language is set to Norwegian (Bokmål).
6) Wait up to 24 hours.
7) The clock's background will begin to flash, and sometimes have an odd lag effect for the seconds counter.

## Expected behaviour

ElevenClock does not flash or lag.

## Screenshots

https://user-images.githubusercontent.com/22780683/213908615-7aaba8e3-f3fd-4b32-8644-43ebed47da18.mp4

## The Log

```
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.004002094268798828 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.9.6 (v3.96) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "nb"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(1240, 2514, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH.mm
🔵 Loaded date time format: %H.%M.%S 
%d.%m.%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (0, 0, 1440, 2560)
can't parse ""
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(-200, 1034, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH.mm
🔵 Loaded date time format: %H.%M.%S 
%d.%m.%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (-1920, 0, 0, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
can't parse ""
🟢 Loaded clocks in 0.8189601898193359
🔵 Restart loop: 1
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
{'System language': 'default', 'Arabic - عربي\u200e (68%)': 'ar', 'Bosnian - Bosanski (6%)': 'bs', 'Bulgarian - български (18%)': 'bg', 'Catalan - Català': 'ca', 'Czech - Čeština': 'cs', 'Danish - Dansk (99%)': 'da', 'German - Deutsch (99%)': 'de', 'Greek - Ελληνικά (18%)': 'el', 'English - English': 'en', 'Spanish - Español (99%)': 'es', 'Estonian - eesti (92%)': 'et', 'Persian - فارسی\u200e (5%)': 'fa', 'Finnish - Suomi (63%)': 'fi', 'French - Français': 'fr', 'Hebrew - עִבְרִית\u200e (92%)': 'he', 'Croatian - Hrvatski (11%)': 'hr', 'Hungarian - Magyar': 'hu', 'Indonesian - Bahasa Indonesia (92%)': 'id', 'Italian - Italiano (81%)': 'it', 'Japanese - 日本語': 'ja', 'Korean - 한국어': 'ko', 'Lithuanian - Lietuvių (22%)': 'lt', 'Latvian - Latviski (61%)': 'lv', 'Norwegian (bokmål) (95%)': 'nb', 'Dutch - Nederlands (91%)': 'nl', 'Norwegian (nynorsk) (67%)': 'nn', 'Polish - Polski (98%)': 'pl', 'Portuguese (Brazil)': 'pt_BR', 'Portuguese (Portugal)': 'pt_PT', 'Romanian - Română (92%)': 'ro', 'Russian - Русский (92%)': 'ru', 'Sinhala - සිංහල': 'si', 'Slovak - Slovenčina (30%)': 'sk', 'Serbian - Srpski (22%)': 'sr', 'Swedish - Svenska (78%)': 'sv', 'Thai - ภาษาไทย (82%)': 'th', 'Turkish - Türkçe (99%)': 'tr', 'Ukranian - Yкраї́нська': 'ua', 'Vietnamese - Tiếng Việt (49%)': 'vi', 'Simplified Chinese (China)': 'zh_CN', 'Traditional Chinese (Taiwan)': 'zh_TW'}
🔵 Language file up-to-date
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 3.6306276321411133
🟠 Can't remove lock file, file exist status: False
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟡 Verifying unverified hwnd 263358
🟡 Fullscreen window detected! (0, 0, 1440, 2560) Fullscreen rect: [0, 0, 1440, 2560]
🟡 Blacklisted hwnd 263358 under title Windows-inndataopplevelse (Process name is c:\windows\systemapps\microsoftwindows.client.cbs_cw5n1h2txyewy\textinputhost.exe)
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 517, in wrap_socket

🔴   File "ssl.py", line 1075, in _create

🔴   File "ssl.py", line 1346, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 132, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>)
🔵 Version URL: http://ww25.somepythonthings.tk/versions/elevenclock.ver?subid1=20230122-0759-5353-bf67-fa8e8ddbe92e
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 140, in updateIfPossible

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 517, in wrap_socket

🔴   File "ssl.py", line 1075, in _create

🔴   File "ssl.py", line 1346, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 132, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>)
🔵 Version URL: http://ww25.somepythonthings.tk/versions/elevenclock.ver?subid1=20230122-0801-01bd-9860-ba2646f5051b
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 140, in updateIfPossible

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 517, in wrap_socket

🔴   File "ssl.py", line 1075, in _create

🔴   File "ssl.py", line 1346, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 132, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>)
🔵 Version URL: http://ww25.somepythonthings.tk/versions/elevenclock.ver?subid1=20230122-1001-08b9-a0b1-edb950ac145b
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 140, in updateIfPossible

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 517, in wrap_socket

🔴   File "ssl.py", line 1075, in _create

🔴   File "ssl.py", line 1346, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 132, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>)
🔵 Version URL: http://ww25.somepythonthings.tk/versions/elevenclock.ver?subid1=20230122-1201-16c4-a16e-beedb2d68794
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 140, in updateIfPossible

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 517, in wrap_socket

🔴   File "ssl.py", line 1075, in _create

🔴   File "ssl.py", line 1346, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 132, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>)
🔵 Version URL: http://ww25.somepythonthings.tk/versions/elevenclock.ver?subid1=20230122-1401-2453-9207-dd5ea3aeae44
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 140, in updateIfPossible

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 517, in wrap_socket

🔴   File "ssl.py", line 1075, in _create

🔴   File "ssl.py", line 1346, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 132, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>)
🔵 Version URL: http://ww25.somepythonthings.tk/versions/elevenclock.ver?subid1=20230122-1601-326d-80db-50db09ddbc6b
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 140, in updateIfPossible

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 517, in wrap_socket

🔴   File "ssl.py", line 1075, in _create

🔴   File "ssl.py", line 1346, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 132, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>)
🔵 Version URL: http://ww25.somepythonthings.tk/versions/elevenclock.ver?subid1=20230122-1801-40b9-a170-2f5ab0b5d18c
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 140, in updateIfPossible

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(1240, 2514, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH.mm
🔵 Loaded date time format: %H.%M.%S 
%d.%m.%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (0, 0, 1440, 2560)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(-200, 2384, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH.mm
🔵 Loaded date time format: %H.%M.%S 
%d.%m.%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (-1080, 510, 0, 2430)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH.mm
🔵 Loaded date time format: %H.%M.%S 
%d.%m.%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Restart loop: 1
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Restart loop: 1
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(-200, 2152, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH.mm
🔵 Loaded date time format: %H.%M.%S 
%d.%m.%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (-1080, 278, 0, 2198)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH.mm
🔵 Loaded date time format: %H.%M.%S 
%d.%m.%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH.mm
🔵 Loaded date time format: %H.%M.%S 
%d.%m.%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(1240, 2514, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH.mm
🔵 Loaded date time format: %H.%M.%S 
%d.%m.%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (0, 0, 1440, 2560)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(-200, 2384, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH.mm
🔵 Loaded date time format: %H.%M.%S 
%d.%m.%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (-1080, 510, 0, 2430)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH.mm
🔵 Loaded date time format: %H.%M.%S 
%d.%m.%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Restart loop: 1
🔵 Showing tooltip
🔵 Long date string: dddd d. MMMM yyyy
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 517, in wrap_socket

🔴   File "ssl.py", line 1075, in _create

🔴   File "ssl.py", line 1346, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 132, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'versions.somepythonthings.tk'. (_ssl.c:992)>)
🔵 Version URL: http://ww25.somepythonthings.tk/versions/elevenclock.ver?subid1=20230122-2001-4730-a9c4-acc8b984b178
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 140, in updateIfPossible

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
Action: ('win', 'n')
🔵 Showing tooltip
🔵 Long date string: dddd d. MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d. MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d. MMMM yyyy
Action: ('win', 'n')
🔵 Showing tooltip
🔵 Long date string: dddd d. MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d. MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d. MMMM yyyy
🔵 Announcement URL: http://ww25.somepythonthings.tk/resources/elevenclock.announcement?subid1=20230122-2012-07ce-95a0-499245fddde6
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 517, in wrap_socket

🔴   File "ssl.py", line 1075, in _create

🔴   File "ssl.py", line 1346, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.somepythonthings.tk'. (_ssl.c:992)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3042, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.somepythonthings.tk'. (_ssl.c:992)>

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3051, in loadAnnouncements

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔵 Copying log to the clipboard...
```

## Additional context
Although I acknowledge that the issue appears to not have occured to many people, I presume that limiting ElevenClock to one instance at a time would hopefully fix it.

As an aside note, I notice in the log above that all references (if any) in ElevenClock's code to `somepythonthings.tk` should be removed as soon as feasible, since domains that start with numbers between `ww5.` and `ww50.` can be assumed to have elapsed and bought by SEO/malware spreaders (Even more so when using the .tk TLD), and a quick Google search for `somepythonthings.tk` seems to confirm my thoughts about it.

**Comment by marticliment** [comment]
> Although I acknowledge that the issue appears to not have occured to many people, I presume that limiting ElevenClock to one instance at a time would hopefully fix it.

This issue is caused due to the inability of the multiple instance handler to close other instances. This faillure is commonly caused by permissions on the .elevenclock folderplaced in your user directory, so please navigate there and delete any ElevenClockRunningXXXXXXXXX file.

P.D. The issues with the domain are happening because freenom has had issues with servers and they have lost lots of records, and won't allow registering new domains.I fixed this on v4.0, but, since the old domain is down, the updater does not work,so please update manually to version 4.0. v4.0 and newer depend on a .com domain registered with google, so there shouldn't be further issues

Please let me know if this fixes the issue

**Comment by DandelionSprout** [comment]
Strangely, the Microsoft Store page seems to install 3.9.3 instead of anything newer, but I've installed 4.0.0 from GitHub now. I'll see if I can remember to let you know about any news after I've tested it for 1~4 days.

**Comment by marticliment** [comment]
Yes, microsoft store is still reviewing version 4.0, and until they publish v4.0 3.9.3 will be the latest version available

**Comment by oubeichen** [comment]
I have upgraded elevenclock to version 4.0 but this issue still exists.

**Comment by marticliment** [comment]
Hi,  may I ask you how did you upgrade to version 4.0.X?

**Comment by DandelionSprout** [comment]
Okay, so it ended up taking me 3 weeks to test, as I could only test new approaches once a day, but I *think* (pressure on "think") that turning on "Enable silent updates" fixes it.

**Comment by oubeichen** [comment]
@marticliment https://github.com/marticliment/ElevenClock/releases

**Comment by marticliment** [comment]
@DandelionSprout, it should not be related, but if it really fixes the issue, please let me know.

@oubeichen, have you ever ran ElevenClock or the installer with administrator rights?

**Comment by DandelionSprout** [comment]
Okay, so you were right that my "update check" theory was wrong, as not even turning off ElevenClock updates entirely fixed it.

My current theory is something related to when Windows enters sleep mode, with the area marked in orange below being files that were specifically changed by the OS circa around the time my PC last entered sleep mode this morning:

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/221373188-4af510e4-3208-4daa-ab73-acec5d3fddb6.png)

</details>

**Comment by marticliment** [comment]
Could you please test this beta build?

https://github.com/marticliment/ElevenClock/releases/download/4.1.0-beta/ElevenClock.Installer.exe

**Comment by DandelionSprout** [comment]
Although I was a bit distracted in the past month, the problem seems to be gone/fixed as of 4.1.0 stable on my end.
