### ISSUE TITLE
[FEATURE REQUEST] I would like ElevenClock to be modifiable at both ends of the taskbar.

### ISSUE THREAD

**Issue by Dhyfer1** [marticliment/ElevenClock#912]
Hi.

ElevenClock adds a layer over the main Windows clock, but if in the ElevenClock settings I choose the option "Show the clock at the left of the screen" the layer moves to the left side exposing the default Windows clock.

I would like ElevenClock to be able to add another layer on the other side of the taskbar, and have the second layer also act as the first layer. In other words, I would like ElevenClock to show the clock on the left side and the date on the right side, as in the example image.

![image_1](https://user-images.githubusercontent.com/50301201/189430188-15c7f748-e841-4f36-b78d-24403ae3ceaf.png)

This could be done if ElevenClock creates a second layer, and that this second layer can be editable as it can be done with the main layer.

I hope you will take my suggestion into consideration. Thank you.

**Comment by martinet101** [comment]
Hi, 

I understand you want two clocks.

Is thisa right?

**Comment by Dhyfer1** [comment]
Hi.

That's right. As I said before, I would like Elevenclock to add a second layer at the other end of the taskbar, but without the need to move or delete the main layer on the right of the taskbar, this way in the left layer I could place the format I want: Weekday, Week number, Only date etc, and that this second layer is also as modifiable as the main layer that hides the Windows clock. In short, that Elevenclock can create two layers, each on either side of the taskbar, and in each one I can customize it to my liking.

Another thing, I use [TranslucentTB](https://github.com/TranslucentTB/TranslucentTB) to apply an acrylic effect on the taskbar, but when Elevenclock is activated, the left border of the layer that hides the main clock highlights over the taskbar, as you can see in the attached image if you zoom in. In the previous image you can also see that the left edge of the layer is highlighted over the taskbar.

![image_10](https://user-images.githubusercontent.com/50301201/189495955-ea275c12-dc3c-4195-9f08-87c8b51c3c65.png)

So could Elevenclock in a future version, apply an acrylic effect to the layer that hides the clock, and that this acrylic effect takes into account the desktop background image as TranslucenTB does?

**Comment by martinet101** [comment]
> Another thing, I use [TranslucentTB](https://github.com/TranslucentTB/TranslucentTB) to apply an acrylic effect on the taskbar, but when Elevenclock is activated, the left border of the layer that hides the main clock highlights over the taskbar, as you can see in the attached image if you zoom in. In the previous image you can also see that the left edge of the layer is highlighted over the taskbar.

For this, you just need to adjust speciric height and y position offset in the settings window, By moving the clock a little downwards, the pixel from where the bg color is calculated will be in the taskbar, providing a moere natural effect.

About the second clock, i'll consider it, though i'm not sure how to integrate this feature.

**Comment by Dhyfer1** [comment]
> For this, you just need to adjust speciric height and y position offset in the settings window, By moving the clock a little downwards, the pixel from where the bg color is calculated will be in the taskbar, providing a moere natural effect.

I have done what you say, but it doesn't look the same. After adjusting the height and position, the background color of the elevenclock clock doesn't adapt very well to the desktop background, as you can see in the image.

![47BfXD5KeO](https://user-images.githubusercontent.com/50301201/191402582-6fa08a01-704e-49d9-9c64-bdae167b78a0.png)

As I said before, I use TranslucentTB to apply an acrylic effect on the taskbar. Without elevenclock (image on the left) the acrylic effect can be seen behind the clock, this acrylic effect takes into account the desktop background image. With elevenclock (image on the right) the clock color only takes into account the accent color in the Windows settings, but in the elevenclock settings my clock style is the "Default" style that I chose in the welcome wizard. The acrylic effect that TranslucentTB applies on the whole taskbar is lost in the clock view after installing elevenclock, I would like that elevenclock could be compatible with TranslucentTB in a future version.
 
> About the second clock, i'll consider it, though i'm not sure how to integrate this feature.

Sure you can. In an elevenclock release you integrated a function in the experimental settings to hide the main clock, and the elevenclock clock could be shown on the left of the taskbar. Check issue #843 where you say "Although now I am thinking that a clock that hid (kind of) the defailkt clock could be an option. It would be just using the same overlay elevenclock uses now but without text on it" But this overlay you mention can go back to having text and create another overlay for the left corner of the taskbar.

**Comment by martinet101** [comment]
> Sure you can. In an elevenclock release you integrated a function in the experimental settings to hide the main clock, and the elevenclock clock could be shown on the left of the taskbar. Check issue #843 where you say "_Although now I am thinking that a clock that hid (kind of) the defailkt clock could be an option. It would be just using the same overlay elevenclock uses now but without text on it_" But this overlay you mention can go back to having text and create another overlay for the left side of the taskbar.

Makes sense




> As I said before, I use TranslucentTB to apply an acrylic effect on the taskbar. Without elevenclock (image on the left) the acrylic effect can be seen behind the clock, this acrylic effect takes into account the desktop background image. With elevenclock (image on the right) the clock color only takes into account the accent color in the Windows settings, but in the elevenclock settings my clock style is the "Default" style that I chose in the welcome wizard. The acrylic effect that TranslucentTB applies on the whole taskbar is lost in the clock view after installing elevenclock, I would like that elevenclock could be compatible with TranslucentTB in a future version.
> 
> >

The bg color is calculated by getting the top-left pixel color and then applying it to the background. So it is not really transparent. If I were to use the default _fluent_ texture, it would look horrible (trust me, i tried it and, since it blends the background and the text of the window clock it looks awful.) The actual one is the best approach that I have managed to get, so this feature can't be improved to be compatible with RoundedTB. 
Also, im my point of view, what I can see in the pics doesn't look _bad_ or _out of place_, but rather it looks _different_ to the effect provided by RoundedTB, so i guess it will be matter of getting used to it, becuase this can't be fixed.

I'll work on the second clock!

**Comment by Dhyfer1** [comment]
Hi. It's not RoundedTB that I mentioned (I also use it, but RoundedTB only creates rounded corners for the taskbar and is compatible with TranslucentTB, which can apply various effects to the taskbar (opaque, clear, blur and acrylic)).

>Also, im my point of view, what I can see in the pics doesn't look bad or out of place, but rather it looks different to the effect provided by RoundedTB, so i guess it will be matter of getting used to it, becuase this can't be fixed.

It's a pity, it's okay, I guess I'll have to get used to it.

> I'll work on the second clock!

Great, I can't wait for the next version! :D

**Comment by martinet101** [comment]
This issue has been fixed

**Comment by Dhyfer1** [comment]
> This issue has been fixed

How? although I can see a second clock on the left side of the screen with the option "Show a second clock on the other end of the taskbar" in Elevenclock settings>Clock settings, this second clock is still not modifiable. As I said before, I would like to see only the clock on the left side and only the date on the right side.

**Comment by Dhyfer1** [comment]
I thought you understood me. I'll say it again (just look at the first example image in this issue), what I want is to be able to see the clock on the left side of the taskbar and the date on the right side of the taskbar. In short, to have a different format on both sides of the taskbar.

If I have the clock on both sides of the taskbar, if I modify one of them to apply, for example, the format time with week number, the same format is automatically applied on the other clock, and what I want is that both sides of the taskbar are different. Do you understand?

**Comment by martinet101** [comment]
Yes yes, I got that on your last message, I just didn't understand at the atart of the issue

**Comment by Dhyfer1** [comment]
Okay, now that you understand it, can you apply it to Elevenclock?

**Comment by martinet101** [comment]
yes, i will

**Comment by Dhyfer1** [comment]
It's ok, take your time. I hope you can implement it later, because I would really like Elevenclock to be able to have the function I ask for.

Thanks in advance

**Comment by marticliment** [comment]
![image](https://user-images.githubusercontent.com/53119851/210229739-fa5341b6-c956-4022-a191-4b7095ad7a2b.png)
Late, but it's coming👀

**Comment by marticliment** [comment]
This feature has been implemented and will come with ElevenClock version 4.0.0

**Comment by Dhyfer1** [comment]
> ![image](https://user-images.githubusercontent.com/53119851/210229739-fa5341b6-c956-4022-a191-4b7095ad7a2b.png) Late, but it's coming👀
> This feature has been implemented and will come with ElevenClock version 4.0.0

What great news! I hope to see that update as soon as possible. 😀

**Comment by marticliment** [comment]
Yes, ElevenClock 4.0.0 will arrive soon

**Comment by albiek1976** [comment]
Thanks for all you do!! Be sure to check your donations!!
